apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../apps/pipeline/upstream/env/platform-agnostic-pns/

patchesStrategicMerge:
- patches/patch-minio-deployment-for-azure.yaml
- patches/delete-minio-pvc.yaml

secretGenerator:
- name: mlpipeline-minio-artifact
  type: Opaque
  behavior: replace
  envs:
  - secret_params.env


