apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../../common/oidc-authservice/base

configMapGenerator:
- name: oidc-authservice-parameters
  behavior: merge
  envs:
  - params.env

secretGenerator:
- name: oidc-authservice-client
  type: Opaque
  behavior: replace
  envs:
  - secret_params.env